### ISSUE TITLE
Failed to resolve: com.github.WhatWeCan:TCPClient:v1.0.2 

### ISSUE THREAD

**Issue by kolyneh** [WhatWeCan/TCPClient#1]
Error:(48, 20) Failed to resolve: com.github.WhatWeCan:TCPClient:v1.0.2

但是  com.github.WhatWeCan:TCPClient:v1.0.1 是OK的，
请问是什么原因呢？

**Comment by WhatWeCan** [comment]
请问还有这样的问题吗 才看到呢  在当前项目中compile了 成功的呢

**Comment by kolyneh** [comment]
不好意思, 上次匆忙关闭了没有写原因。

1.0.2版本按照您的导入说明里写：  url 'https://jitpack.io'  是不行的，加上"www"就可以了，

如下：
allprojects {
    repositories {
     
        maven { url 'https://www.jitpack.io' }
    }
}

**Comment by WhatWeCan** [comment]
嗯 这都行 厉害厉害
